AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SchmittAwsLabAudioSummmaryMp3:
    Type: AWS::Lambda::Function
    Properties:
      Role: arn:aws:iam::331867785991:role/SchmittAwsLabAudioSummmaryMp3Role
      Runtime: nodejs24.x
      Handler: index.handler
      FunctionName: schmitt-aws-lab-audio-summary-mp3
      Code:
        ZipFile: |
          exports.handler = async () => ({ statusCode: 200 });
