AWSTemplateFormatVersion: "2010-09-09"
Resources:
  DeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "DeployRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              #Service:
              #  - "lambda.amazonaws.com"
              AWS:
                - "arn:aws:iam::331867785991:user/deploy"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "S3BucketCreation"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:CreateBucket"
                Resource:
                  - "*"
        - PolicyName: "S3BucketNotificationCreation"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:PutBucketNotification"
                Resource:
                  - "arn:aws:s3:::schmitt-aws-lab-audio-summary-mp3"
        - PolicyName: "CloudFormationGeneralAllow"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:GetTemplateSummary"
                  - "cloudformation:CreateChangeSet"
                  - "cloudformation:ExecuteChangeSet"
                  - "cloudformation:DescribeChangeSet"
                  - "cloudformation:CreateStack"
                  - "cloudformation:UpdateStack"
                  - "cloudformation:DeleteStack"
                Resource:
                  - "arn:aws:cloudformation:us-east-2:331867785991:stack/*"
        - PolicyName: "CloudFormationDenyRootCreated"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Deny
                Action:
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:GetTemplateSummary"
                  - "cloudformation:CreateChangeSet"
                  - "cloudformation:ExecuteChangeSet"
                  - "cloudformation:DescribeChangeSet"
                  - "cloudformation:CreateStack"
                  - "cloudformation:UpdateStack"
                  - "cloudformation:DeleteStack"
                  - "cloudformation:DeleteStack"
                Resource:
                  - "arn:aws:cloudformation:us-east-2:331867785991:stack/role-policy-template"
                  - "arn:aws:cloudformation:us-east-2:331867785991:stack/create-deploy-user"
        - PolicyName: "Lambda"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:CreateFunction"
                  - "lambda:UpdateFunctionCode"
                  - "lambda:DeleteFunction"
                  - "lambda:GetFunction"
                  - "lambda:ListFunctions"
                  - "lambda:UpdateFunctionConfiguration"
                  - "lambda:AddPermission"
                  - "lambda:RemovePermission"
                Resource: "arn:aws:lambda:us-east-2:331867785991:function:*"
              - Effect: Allow
                Action:
                  - "iam:PassRole"
                Resource: # References `LambdaRole` section of the template
                  - !GetAtt AudioSummaryS3LambdaRole.Arn
                  - !GetAtt AudioSummaryLinkedLambdaRole.Arn
                  - !GetAtt AudioSummarySyncLambdaRole.Arn
                  - !GetAtt AudioSummaryTruncateLambdaRole.Arn
                  - !GetAtt AudioSummaryGetLambdaRole.Arn
                    # note: generic 'AWS::EarlyValidation::PropertyValidation' failure if new ARNs left out
                    # understand the relationship between this and the lambda tempalte
        - PolicyName: "CloudWatchLogs"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                Resource: "arn:aws:logs:us-east-2:331867785991:*"
              - Effect: Allow
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DeleteLogGroup"
                  - "logs:DescribeLogGroups"
                Resource: "arn:aws:logs:us-east-2:331867785991:log-group:/aws/lambda/schmitt-aws-lab-audio-summary-mp3:*"
        - PolicyName: "Secrets"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "ssm:GetParameters"
                  - "ssm:PutParameter"
                  - "ssm:GetParameter"
                  - "ssm:DeleteParameter"
                Resource: arn:aws:ssm:us-east-2:331867785991:parameter/lambda/geminiApiKey
        - PolicyName: "DynamoManagement"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:CreateTable"
                  - "dynamodb:DeleteTable"
                  - "dynamodb:DescribeTable"
                  - "dynamodb:UpdateTable"
                Resource: arn:aws:dynamodb:us-east-2:331867785991:table/audio-summary-batches
  AudioSummaryS3LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "AudioSummaryS3LambdaRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "S3BucketLambda"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:DeleteObject"
                Resource:
                  - "arn:aws:s3:::schmitt-aws-lab-audio-summary-mp3"
                  - "arn:aws:s3:::schmitt-aws-lab-audio-summary-mp3/*"
        - PolicyName: "CloudWatchLogs"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:PutRetentionPolicy"
                  - "logs:DeleteLogGroup"
                  - "logs:DescribeLogGroups"
                Resource: "arn:aws:logs:us-east-2:331867785991:*"
                # The below did not work, for reasons not obvious to me:
                # Resource: "arn:aws:logs:us-east-2:331867785991:log-group:/aws/lambda/schmitt-aws-lab-audio-summary-mp3"
              - Effect: Allow
                Action:
                  - "logs:PutLogEvents"
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                Resource: "arn:aws:logs:us-east-2:331867785991:*"
        - PolicyName: "DynamoAccess"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:PutItem"
                Resource: arn:aws:dynamodb:us-east-2:331867785991:table/audio-summary-batches
  AudioSummaryLinkedLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "AudioSummaryLinkedLambdaRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "S3BucketLambda"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:DeleteObject"
                Resource:
                  - "arn:aws:s3:::schmitt-aws-lab-audio-summary-feed"
                  - "arn:aws:s3:::schmitt-aws-lab-audio-summary-feed/*"
        - PolicyName: "CloudWatchLogs"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:PutRetentionPolicy"
                  - "logs:DeleteLogGroup"
                  - "logs:DescribeLogGroups"
                Resource: "arn:aws:logs:us-east-2:331867785991:*"
              - Effect: Allow
                Action:
                  - "logs:PutLogEvents"
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                Resource: "arn:aws:logs:us-east-2:331867785991:*"
        - PolicyName: "Secrets"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "ssm:GetParameter"
                Resource: arn:aws:ssm:us-east-2:331867785991:parameter/lambda/geminiApiKey
        - PolicyName: "DynamoAccess"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:PutItem"
                Resource: arn:aws:dynamodb:us-east-2:331867785991:table/audio-summary-batches
  AudioSummarySyncLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "AudioSummarySyncLambdaRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "DynamoAccess"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:Scan"
                  - "dynamodb:DeleteItem"
                Resource: arn:aws:dynamodb:us-east-2:331867785991:table/audio-summary-batches
  AudioSummaryTruncateLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "AudioSummaryTruncateLambdaRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "S3BucketLambda"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                Resource:
                  - "arn:aws:s3:::schmitt-aws-lab-audio-summary-feed"
                  - "arn:aws:s3:::schmitt-aws-lab-audio-summary-feed/*"
  AudioSummaryGetLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "AudioSummaryGetLambdaRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "S3BucketLambda"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:PutObject"
                Resource:
                  - "arn:aws:s3:::schmitt-aws-lab-audio-summary-feed"
                  - "arn:aws:s3:::schmitt-aws-lab-audio-summary-feed/*"
