AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SchmittAwsLabAudioSummaryMp3:
    Type: AWS::S3::Bucket
    DependsOn: S3InvokeLambdaPermission
    DeletionPolicy: Delete
    Properties:
      BucketName: "schmitt-aws-lab-audio-summary-mp3"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !GetAtt AudioSummaryS3Lambda.Arn

  SchmittAwsLabAudioSummaryFeed:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: "schmitt-aws-lab-audio-summary-feed"

  SchmittAwsLabLambdaBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: "schmitt-aws-lab-lambda"

  AudioSummaryBatchesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "audio-summary-batches"
      AttributeDefinitions:
        - AttributeName: slug
          AttributeType: S
        - AttributeName: resourceLink
          AttributeType: S
        # document store: thought I needed to provide these, maybe I'm too relational brained
        #- AttributeName: geminiBatchName
        #  AttributeType: S
        #- AttributeName: geminiFileName
        #  AttributeType: S
        #- AttributeName: createdAt
        #  AttributeType: S
      KeySchema:
        - AttributeName: slug
          KeyType: HASH
        - AttributeName: resourceLink
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  # Used for MP3 files dropped into `schmitt-aws-lab-audio-summary-mp3`
  AudioSummaryS3Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Role: arn:aws:iam::331867785991:role/AudioSummaryS3LambdaRole
      Runtime: nodejs24.x
      Handler: index.handler
      FunctionName: schmitt-aws-lab-audio-summary-s3
      Code:
        ZipFile: |
          exports.handler = async () => ({ statusCode: 200 });


  S3InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn: AudioSummaryS3Lambda
    Properties:
      FunctionName: !GetAtt AudioSummaryS3Lambda.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: "arn:aws:s3:::schmitt-aws-lab-audio-summary-mp3"

  # Used for requests with link + metadata specified
  AudioSummaryLinkedLambda:
    Type: AWS::Lambda::Function
    Properties:
      Role: arn:aws:iam::331867785991:role/AudioSummaryLinkedLambdaRole
      Runtime: nodejs24.x
      Handler: index.handler
      FunctionName: schmitt-aws-lab-audio-summary-linked
      Timeout: 900
      Code:
        ZipFile: |
          exports.handler = async () => ({ statusCode: 200 });
